[workspace]
members = [
    "main"
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.93.0"
repository = "https://github.com/GeForceLegend/vscode-mcshader"

[profile.release]
lto = "thin"
strip = "symbols"
codegen-units = 1

[profile.dev]
debug = false
strip = "debuginfo"

[workspace.lints.clippy]
missing_const_for_fn = "warn"
use_self = "warn"
match_same_arms = "warn"
non_std_lazy_statics = "warn"
